version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
  build:
    commands:
      - echo "Running Lambda unit tests..."
      - python3 -m unittest test_lambda.py
      - echo "Zipping Lambda package and appspec..."
      - zip -r lambda-deploy-package.zip lambda_function.py appspec.yaml
  post_build:
    commands:
      - echo "Publishing new Lambda version..."
      - VERSION=$(aws lambda publish-version --function-name HelloWorldFunction --query 'Version' --output text)
      - echo "Updating 'live' alias to version $VERSION"
      - aws lambda update-alias --function-name HelloWorldFunction --name live --function-version $VERSION

artifacts:
  files:
    - lambda-deploy-package.zip
    - appspec.yaml
